research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any accurate and concise information about {topic}
    from the provided source website. 
  expected_output: >
    {topic} related data including title, updated date and time information and url <a href> html tag contents from each item title

data_formatting_task:
  description: >
    Review the context you got and format each set of data into a JSON object.
    Make sure the JSON object contains key / value pairs for each of the pieces of data within each set including title, updated date and time information and further information links

  expected_output: >
    A formatted JSON object containing key / value pairs containing the expected data

data_filter_task:
  description: >
    Review the context you got and filter the data to only include results relating to {location}.
    Return the results in the same {format} format you recieved them in, including all key / value pairs received
  expected_output: >
    Filtered data only returning JSON objects that contain {location}



